// seeds
const SEED_PREFIX_AUTHORITY_SIGNER = "authority_signer"
const SEED_PREFIX_CUSTODY_SIGNER = "custody_signer"
const SEED_PREFIX_MINT_AUTHORITY = "mint_signer"
const SEED_PREFIX_SENDER = "sender"
const SEED_PREFIX_REDEEMER = "redeemer"
const SEED_PREFIX_EMITTER = "emitter"
const SEED_PREFIX_FOREIGN_CONTRACT = "foreign_contract"
const SEED_PREFIX_TMP = "tmp"
const SEED_PREFIX_CONFIG = "config"
const SEED_PREFIX_BRIDGE = "Bridge"
const SEED_PREFIX_SEQUENCE = "Sequence"
const SEED_PREFIX_FEE_COLLECTOR = "fee_collector"
const SEED_PREFIX_FEE_BRIDGED = "bridged"

export {
  SEED_PREFIX_AUTHORITY_SIGNER,
  SEED_PREFIX_CUSTODY_SIGNER,
  SEED_PREFIX_EMITTER,
  SEED_PREFIX_MINT_AUTHORITY,
  SEED_PREFIX_REDEEMER,
  SEED_PREFIX_SENDER,
  SEED_PREFIX_FOREIGN_CONTRACT,
  SEED_PREFIX_TMP,
  SEED_PREFIX_CONFIG,
  SEED_PREFIX_BRIDGE,
  SEED_PREFIX_SEQUENCE,
  SEED_PREFIX_FEE_COLLECTOR,
  SEED_PREFIX_FEE_BRIDGED,
}